### ISSUE TITLE
What the 'bug' means?

### ISSUE THREAD

**Issue by HAN-oQo** [lucidrains/deformable-attention#1]
Hi, thank you for awesome project.
I wonder what the bug means.
Does it means it's not working yet?

**Comment by lucidrains** [comment]
@hanq0212 oh hey, nope that commit refers to a bug fix where the coordinates were not perfectly aligned with centers of the convolutional kernel - it should be fine now! :crossed_fingers:

**Comment by HAN-oQo** [comment]
@lucidrains
Thank you so much!!!
