### ISSUE TITLE
Should be 'xy' instead of 'ij'?

### ISSUE THREAD

**Issue by kareido** [lucidrains/deformable-attention#6]
https://github.com/lucidrains/deformable-attention/blob/e030def94b896a21d0b4f41c37e2183945856bc2/deformable_attention/deformable_attention_2d.py#L26

Thanks for sharing your implementation. Since you use ```F.grid_sample``` afterwards, it treats each point as ```[x, y]``` not ```[y, x]``` (see [doc](https://pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html)). Also, in the official repo, they do have an extra swap [here](https://github.com/LeapLabTHU/DAT/blob/main/models/dat_blocks.py#LL245C33-L245C33).

Sincerely,
Zhe

**Comment by lucidrains** [comment]
@kareido oh yes, i do believe you are right! thanks for catching this error

**Comment by kareido** [comment]
resolved

**Comment by qibin0506** [comment]
@lucidrains @kareido need to modify [deformable_attention_3d.py](https://github.com/lucidrains/deformable-attention/blob/main/deformable_attention/deformable_attention_3d.py#L30)?
